### ISSUE TITLE
Adjusting Card Count Puts Focus on Filter

### ISSUE THREAD

**Issue by joezimjs** [Sydtrack/ringsdb#16]
When I click on a card and it brings up the overlay where I can adjust the count in the deck and side board, if I click a number to adjust how many are in the deck/side board, then the overlay closes and focus immediately goes to the filter input, which (on my phone) scrolls me up/down and opens my keyboard, which then requires me to close the keyboard and scroll back to where I was.

See video: http://screencast.com/t/E7muYhesHZOO

**Comment by Sydtrack** [comment]
In desktop deck building, this is a feature. You can build an entire deck without using your mouse. Just type the card name, use arrows to select it and press enter. On the card overlay, type 0, 1, 2 or 3 in your keyboard and the desired amount will be set. Then, as the focus goes back to the input, you can just type the next card to start all over again.

Since this is a problem in mobile, I will disable the focus on mobile environments.

**Comment by joezimjs** [comment]
Great. Thanks!
