### ISSUE TITLE
Decks Classification

### ISSUE THREAD

**Issue by pirinisz** [Sydtrack/ringsdb#45]
Goodmorning and congratulations on this great project. I use RingsDB a lot and wanted to make a suggestion: You already have some categories to the Decklists page (Popular, Recent, Hot Topics etc) but I think it would be helpful to create another category according to the number of heroes of the decklist (1, 2 or 3).

Thank you in advance for your time.

**Comment by seastan** [comment]
I think your best bet for now is to search for cards that contain Strider. Now that Folco is released it's not easy to tell if a three hero deck is meant to be a two hero deck or not. And I expect true 2-hero decks to disappear because adding Folco will make the deck better in almost all cases. So I have no plans to implement this.
